FROM python:3
WORKDIR /app
RUN apt-get update && apt-get install graphicsmagick -y
# install some ffmpeg deps first, then the rest
# if "Processing triggers for libc-bin" gets too big it crashes (disk space)
RUN apt-get install libc6 libsdl2-2.0-0 libpostproc56 -y
RUN apt-get install ffmpeg -y
RUN apt-get install python3-magic \
    # 30M for moodbar to decode opus, another 40M (and systemd, cryptsetup) to open video/x-matroska
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good -y
COPY requirements.txt .
RUN pip install -r requirements.txt