FROM rakudo-star
WORKDIR /app
# +570MB fun stuff
RUN apt-get update && apt-get install graphicsmagick ffmpeg -y
# < zef usually cant install things because of test fails
RUN zef install --/test Image::Libexif
# < this should all be included in rakudo-star
RUN apt-get install libssl-dev -y
# < find out what 'Build-Essential: yes' in `apt show build-essential` means
RUN apt-get install less build-essential man -y
RUN zef install --/test cro
