// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dOQOPOOO]OPO'#C`OOOO'#Cf'#CfQOOOOOOOOO'#Cc'#CcObOPO'#CbOOOO,58z,58zO]OPO'#CdOjOPO,58|OOOO,59O,59OOOOO-E6b-E6b",
  stateData: "r~OQQORQOTPO~OQSO~OZVOXUX~OZVOXUa~O",
  goto: "qZPPPP[P_bhPnRQORUPQTPRXVQWTRYWRRO",
  nodeNames: "⚠ Program Name Number IOing IOness IOpath Leg",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!b~RW!P!Qk!Q![p!c!}x#T#]x#]#^!T#^#cx#c#d!T#d#ox~pOZ~~uPR~!Q![p~}QQ~!c!}x#T#ox~![QT~Q~!c!}x#T#ox",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
